default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>


development:
  primary:
    <<: *default
    database: pulsetrack_development
    migrations_paths: db/migrate

  queue:
    adapter: sqlite3
    database: storage/queue_development.sqlite3
    pool: 5
    timeout: 5000
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: pulsetrack_test
    migrations_paths: db/migrate
  queue:
    adapter: sqlite3
    database: storage/queue_test.sqlite3
    pool: 5
    timeout: 5000
    migrations_paths: db/queue_migrate

# As with config/credentials.yml, you never want to storsdfasdfe sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    database: pulsetrack_production
    username: pulsetrack
    password: <%= ENV["DATABASE_PASSWORD_PROD"] %>
  cache:
    <<: *primary_production
    database: pulsetrack_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: pulsetrack_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: pulsetrack_production_cable
    migrations_paths: db/cable_migrate
